name: gearnet
channels:
  - milagraph
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bio-embeddings-esm=0.2.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - cairo=1.18.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - colorama=0.4.6
  - contourpy=1.3.0
  - cudatoolkit=11.1.1
  - cycler=0.12.1
  - decorator=5.1.1
  - easydict=1.13
  - expat=2.6.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.0
  - freetype=2.12.1
  - future=1.0.0
  - greenlet=3.1.1
  - icu=73.2
  - importlib-resources=6.4.5
  - importlib_resources=6.4.5
  - jinja2=3.1.4
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.12
  - ld_impl_linux-64=2.43
  - lerc=3.0
  - libblas=3.9.0
  - libboost=1.84.0
  - libboost-python=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libglib=2.80.2
  - libgomp=14.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnsl=2.0.1
  - libpng=1.6.43
  - libpq=16.5
  - libprotobuf=3.16.0
  - librdkit=2024.03.6
  - libsqlite=3.46.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.3.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - llvm-openmp=19.1.3
  - markupsafe=3.0.2
  - matplotlib-base=3.9.2
  - mkl=2020.4
  - munkres=1.1.4
  - ncurses=6.5
  - networkx=3.2.1
  - ninja=1.12.1
  - numpy=1.26.4
  - olefile=0.47
  - openjpeg=2.5.0
  - openssl=3.4.0
  - packaging=24.2
  - pandas=2.2.3
  - pcre2=10.43
  - pillow=8.2.0
  - pip=24.3.1
  - pixman=0.43.2
  - pthread-stubs=0.4
  - pycairo=1.27.0
  - pycparser=2.22
  - pyparsing=3.2.0
  - python=3.9.19
  - python-dateutil=2.9.0.post0
  - python-lmdb=1.5.1
  - python-tzdata=2024.2
  - python_abi=3.9
  - pytz=2024.1
  - pyyaml=6.0.2
  - qhull=2020.2
  - rdkit=2024.03.6
  - readline=8.2
  - reportlab=3.5.68
  - setuptools=75.5.0
  - six=1.16.0
  - sleef=3.7
  - sqlalchemy=2.0.36
  - tk=8.6.13
  - torchdrug=0.2.1
  - tqdm=4.67.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=15.1.0
  - wheel=0.45.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.11.4
      - aiosignal==1.3.1
      - argparse==1.4.0
      - async-timeout==5.0.1
      - atom3d==0.2.6
      - attrs==24.2.0
      - biopython==1.84
      - blosc2==2.5.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cmake==3.25.0
      - dill==0.3.9
      - easy-parallel==0.1.6
      - filelock==3.13.1
      - freesasa==2.2.1
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - h5py==3.12.1
      - huggingface-hub==0.26.2
      - idna==3.10
      - joblib==1.4.2
      - lightning-utilities==0.11.9
      - lit==15.0.7
      - littleutils==0.2.4
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - multiprocess==0.70.17
      - ndindex==1.9.2
      - numexpr==2.10.1
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - ogb==1.3.6
      - outdated==0.2.2
      - pathos==0.3.3
      - pox==0.3.5
      - ppft==1.7.6.9
      - propcache==0.2.0
      - psutil==6.1.0
      - py-cpuinfo==9.0.0
      - pyrr==0.10.3
      - python-dotenv==1.0.1
      - pytorch-lightning==2.0.0
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - sympy==1.13.1
      - tables==3.9.2
      - threadpoolctl==3.5.0
      - tokenizers==0.20.3
      - torch==2.0.1+cu117
      - torch-cluster==1.6.3+pt20cu117
      - torch-geometric==2.6.1
      - torchaudio==2.0.2+cu117
      - torchmetrics==1.6.0
      - torchvision==0.15.2+cu117
      - transformers==4.46.3
      - triton==2.0.0
      - urllib3==2.2.3
      - yacs==0.1.8
      - yarl==1.17.2
prefix: /home/stuhcnga/miniforge3/envs/gearnet
